### ISSUE TITLE
Can't add employees

### ISSUE THREAD

**Issue by mlix8hoblc** [JohnMwendwa/vet-management-system#81]
https://github.com/JohnMwendwa/vet-management-system/assets/110055457/74148a5b-db33-474e-ab35-bf332370f672

**Comment by JohnMwendwa** [comment]
I know where your confusion is, the users of the app are of three categories, namely:
 1. Doctors
 2. Nurses
 3. Clients
 
- For clients and nurses, they can't make any changes on the app i.e adding, editing and removing other users accounts.
- A doctor with the role of an admin is the only one who has the privilege to add, edit or remove users at their discretion.

## Solution to your problem
Now, the solution in regard to your case is simple, go to your database and ensure you give atleast one user the role of a doctor and use that user's account to add, edit or remove other users
